In [14]:
import cv2
import numpy as np
import os


In [9]:
v = np.array([[1,2,1,2],[1,2,1,2]])
v

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [11]:
v = np.array([[1,2,1,2],[1,2,1,2]])
np.hstack((v,v))

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1, 2]])

In [10]:
img = cv2.imread(r"C:\Users\faiya\OneDrive\Desktop\jupyterlab\img 1.jpg")
print(img)

[[[40 46 51]
  [36 42 47]
  [39 45 50]
  ...
  [16 16  4]
  [16 16  4]
  [16 16  4]]

 [[40 46 51]
  [36 42 47]
  [38 44 49]
  ...
  [35 35 23]
  [35 35 23]
  [35 35 23]]

 [[40 46 51]
  [35 41 46]
  [37 43 48]
  ...
  [40 40 28]
  [40 40 28]
  [40 40 28]]

 ...

 [[ 7  8 12]
  [ 6  7 11]
  [ 6  7 11]
  ...
  [29 23 12]
  [29 23 12]
  [29 23 12]]

 [[ 7  8 12]
  [ 6  7 11]
  [ 6  7 11]
  ...
  [29 23 12]
  [29 23 12]
  [29 23 12]]

 [[ 7  8 12]
  [ 6  7 11]
  [ 6  7 11]
  ...
  [29 23 12]
  [29 23 12]
  [29 23 12]]]


In [17]:
img = cv2.imread(r"C:\Users\faiya\OneDrive\Desktop\jupyterlab\img 1.jpg")
re_img = cv2.resize(img, (200, 500))
h = np.hstack((re_img, re_img))
cv2.imshow("Riya", h)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np

img = cv2.imread(r"C:\Users\faiya\OneDrive\Desktop\jupyterlab\img 1.jpg")
re_img = cv2.resize(img, (110, 400))
v = np.vstack((re_img, re_img))
cv2.imshow("Riya", v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
import cv2
import numpy as np

img = cv2.imread(r"C:\Users\faiya\OneDrive\Desktop\jupyterlab\img 1.jpg")
re_img = cv2.resize(img, (100, 200))
v = np.vstack((h,h))
h = np.hstack((re_img, re_img))
cv2.imshow("Riya", v)
cv2.waitKey(0)
cv2.destroyAllWindows()